# Generated by Django 4.1.5 on 2023-02-18 10:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUpdateHolderClientIndividual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique individual contact batch identifier', primary_key=True, serialize=False)),
                ('contact_load_individual_client', models.JSONField()),
                ('update_count', models.IntegerField(default=0)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUpdateHolderCooperate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique cooperate contact batch identifier', primary_key=True, serialize=False)),
                ('contact_load_cooperate_client', models.JSONField()),
                ('update_count', models.IntegerField(default=0)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
