# Generated by Django 4.1.5 on 2023-02-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contactupdateholderclientindividual_contact_load_individual_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactupdateholderclientindividual',
            name='batch',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
