# Generated by Django 4.1.5 on 2023-02-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contactupdateholderclientindividual_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactupdateholdercooperate',
            name='batch',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
