version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: "python3 manage.py runserver 0.0.0.0:8080"
    ports:
      - 8081:8080
    volumes:
      - .:/app

  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:  
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306

    


  # celery_servcie:
  #   command: celery -A freshsales_automations worker -l info
  #   depends_on:
  #     - backend
