version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    # deploy:
    #   resources:
    #       limits:
    #         cpus: 0.50
    #         memory: 4GB
    #       reservations:
    #         cpus: 0.25
    #         memory: 2GB
    command: "python3 manage.py runserver 0.0.0.0:8080"
    ports:
      - 8081:8080
    volumes:
      - .:/app

  # db:
  #   image: mysql:5.7.22

  #   # command:
  #   #     - /bin/sh
  #   #     - -c
  #   #     - |
  #   #       path=$(which msql)
  #   #       export PATH=$PATH:path
  #   #       mysql --max_allowed_packet=32M
  #   #       mysqld --max_allowed_packet=128M

  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: admin
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: root
  #     MYSQL_ROOT_PASSWORD: root
  #   volumes:  
  #     - .dbdata:/var/lib/mysql
  #   ports:
  #     - 33066:3306


  db2:
    image: postgres:14.1-alpine
    restart: always
    # deploy:
    #   resources:
    #       limits:
    #         cpus: 0.50
    #         memory: 512M
    #       reservations:
    #         cpus: 0.25
    #         memory: 128M
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_NAME=postgres
    ports:
      - '5432:5432'
    volumes: 
      - .db2:/var/lib/postgresql/data




# volumes:
#   db2:
#     driver: local
    


  # celery_servcie:
  #   command: celery -A freshsales_automations worker -l info
  #   depends_on:
  #     - backend
